name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p ${{SECRETS.DOCKER_PASSWORD}}
        echo "Finalizando Login"
    - name: Build Docker Image
      run: |
        docker build -t sebratdocker/cron-ticker:graphql
    - name: Push Docker Image
      run: |
        docker push sebratdocker/cron-ticker:graphql
