name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
      run: |
        echo "Iniciando Login"
        docker login -u $DOCKER_USER -p ${{secrets.DOCKER_PASSWORD}}
        echo "Finalizando Login"
    - name: Build Docker Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build -t sebratdocker/cron-ticker:$NEW_VERSION .
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker push sebratdocker/cron-ticker:$NEW_VERSION
        docker image tag sebratdocker/cron-ticker:$NEW_VERSION sebratdocker/cron-ticker:latest
        docker push sebratdocker/cron-ticker:latest
